apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: default-backend
  template:
    metadata:
      labels:
        app: default-backend
    spec:
      containers:
      - name: default-backend
        image: k8s.gcr.io/defaultbackend:1.0
        ports:
        - containerPort: 8080
