version: '2'

services:
  load_balancer:
    image: my_nginx
    volumes:
    - ./load_balancer/config:/etc/nginx
    depends_on:
    - server1
    - server2
    ports:
    - 80:80

  server1:
    image: c-brooks/pg_ping
    expose:
    - 80
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: ""

  server2:
    image: c-brooks/pg_ping
    expose:
    - 80
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: ""

  database:
    image: postgres
    expose:
    - 5432
