version: '2'

services:
  load_balancer:
    image: my_nginx
    networks:
    - frontend
    volumes:
    - ./load_balancer/config:/etc/nginx
    depends_on:
    - server1
    - server2
    ports:
    - 80:80

  server1:
    image: c-brooks/pg_ping
    networks:
    - frontend
    - server
    expose:
    - 80
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: ""
    depends_on:
      database

  server2:
    image: c-brooks/pg_ping
    networks:
    - frontend
    - server
    expose:
    - 80
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: ""
    depends_on:
      database

  database:
    image: postgres
    networks:
    - server
    expose:
    - 5432

networks:
  frontend:
  server:
