version: '2'

services:
  load_balancer:
    image: my_nginx
    networks:
    - frontend
    volumes:
    - ./load_balancer/config:/etc/nginx
    depends_on:
    - server1
    - server2
    ports:
    - 80:80
    mem_limit: 4M
    cpu_quota: 0.1

  server1:
    image: c-brooks/pg_ping
    networks:
    - frontend
    - server
    expose:
    - 80
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: ""

  server2:
    image: c-brooks/pg_ping
    networks:
    - frontend
    - server
    expose:
    - 80
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: ""

  database:
    image: postgres
    networks:
    - server
    expose:
    - 5432

  cadvisor:
    networks:
    - frontend
    - server
    image: google/cadvisor:v0.29.0
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

networks:
  frontend:
  server:

