FROM golang:1.11beta1-stretch

COPY . /go/src/github.com/c-brooks/echo-hostname
WORKDIR /go/src/github.com/c-brooks/echo-hostname

RUN go build -o echo-hostname

RUN \
    apt-get update && apt-get install -y curl

CMD [ "./echo-hostname" ]

EXPOSE 80
