apiVersion: v1
kind: Pod
metadata:
  name: webserver-with-caching
spec:
  containers:

  - name: caching-container
    image: c-brooks/cache-manager
    volumeMounts:
    - mountPath: /data
      name: cache-volume

  - name: webserver
    image: c-brooks/webserver
    volumeMounts:
    - mountPath: /etc/cache
      name: cache-volume

  volumes:
  - name: cache-volume
    emptyDir: {}
