kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: web-allow-test-nginx
spec:
  podSelector: {}
  ingress:
  - from:
      - podSelector:
          matchLabels:
            name: test-nginx
