# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx # notice this selector ...

  replicas: 3

  # 'template' refers to a POD
  template:
    metadata:
      labels:
        app: nginx # matches this label
    spec:
      containers:
      - name: nginx
        image: nginx:1.15
        ports:
        - containerPort: 80
          protocol: TCP
