kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  type: LoadBalancer # will claim an IP
  selector:
    app: nginx       # targets label app=nginx
  ports:
  - port: 80         # expose port 80
    targetPort: 80   # matches the ContainerPort
